# Generated by Django 4.2.17 on 2025-02-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_masuk_surat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
