# Generated by Django 5.1.6 on 2025-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_dokumen_laporan_diunggah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_laporan',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tanggal_masuk_surat',
            field=models.DateField(null=True),
        ),
    ]
